/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.oracly.accounts.payable.data.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.oracly.accounts.payable.data.model.Payable;
import com.liferay.oracly.accounts.payable.data.service.PayableLocalServiceUtil;

/**
 * The extended model base implementation for the Payable service. Represents a row in the &quot;Oracly_Payable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PayableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PayableImpl
 * @see Payable
 * @generated
 */
@ProviderType
public abstract class PayableBaseImpl extends PayableModelImpl
	implements Payable {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a payable model instance should use the {@link Payable} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PayableLocalServiceUtil.addPayable(this);
		}
		else {
			PayableLocalServiceUtil.updatePayable(this);
		}
	}
}